// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestEstrategyTurism.Data.Context;

namespace TestingStrategyTurism.API.Migrations
{
    [DbContext(typeof(TestingEstrategyTurismDbContext))]
    [Migration("20190327205328_seed")]
    partial class seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestEstrategyTurism.Domain.Features.Cars.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AirConditioning");

                    b.Property<string>("Brand")
                        .HasMaxLength(50);

                    b.Property<string>("Model")
                        .HasMaxLength(50);

                    b.Property<int>("Passengers")
                        .HasMaxLength(10);

                    b.Property<string>("Photos");

                    b.Property<int>("Transmission")
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AirConditioning = true,
                            Brand = "Citroen",
                            Model = "C4",
                            Passengers = 5,
                            Transmission = 0
                        });
                });

            modelBuilder.Entity("TestEstrategyTurism.Domain.Features.Hotels.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<int>("Stars")
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Vacaria",
                            Name = "San Bernardo",
                            Stars = 4
                        },
                        new
                        {
                            Id = 2,
                            City = "Lages",
                            Name = "Lages Plaza Hotel",
                            Stars = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
