// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eFlight.Data.Context;

namespace eFlight.API.Migrations
{
    [DbContext(typeof(eFlightDbContext))]
    partial class eFlightDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("eFlight.Domain.Features.Cars.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AirConditioning");

                    b.Property<string>("Brand")
                        .HasMaxLength(50);

                    b.Property<string>("Model")
                        .HasMaxLength(50);

                    b.Property<int>("Passengers")
                        .HasMaxLength(10);

                    b.Property<string>("Photos");

                    b.Property<int>("Transmission")
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AirConditioning = true,
                            Brand = "Citroen",
                            Model = "C4",
                            Passengers = 5,
                            Transmission = 0
                        },
                        new
                        {
                            Id = 2,
                            AirConditioning = true,
                            Brand = "Ford",
                            Model = "New Fiesta",
                            Passengers = 5,
                            Transmission = 0
                        },
                        new
                        {
                            Id = 3,
                            AirConditioning = true,
                            Brand = "Chevrolet",
                            Model = "Onix",
                            Passengers = 5,
                            Transmission = 0
                        },
                        new
                        {
                            Id = 4,
                            AirConditioning = true,
                            Brand = "Hyundai",
                            Model = "HB20",
                            Passengers = 5,
                            Transmission = 0
                        },
                        new
                        {
                            Id = 5,
                            AirConditioning = true,
                            Brand = "Volkswagen",
                            Model = "Gol",
                            Passengers = 5,
                            Transmission = 0
                        },
                        new
                        {
                            Id = 6,
                            AirConditioning = true,
                            Brand = "Fiat",
                            Model = "Argo",
                            Passengers = 5,
                            Transmission = 0
                        });
                });

            modelBuilder.Entity("eFlight.Domain.Features.Hotels.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasMaxLength(50);

                    b.Property<double>("Daily");

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<int>("Stars")
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Paris",
                            Daily = 397.0,
                            Name = "Hotel Darcet",
                            Stars = 0
                        },
                        new
                        {
                            Id = 2,
                            City = "Paris",
                            Daily = 338.0,
                            Name = "Hôtel La Manufacture",
                            Stars = 0
                        },
                        new
                        {
                            Id = 3,
                            City = "Roma",
                            Daily = 859.0,
                            Name = "Hotel Italia",
                            Stars = 0
                        },
                        new
                        {
                            Id = 4,
                            City = "Roma",
                            Daily = 611.0,
                            Name = "Best Western Plus Hotel Universo",
                            Stars = 0
                        },
                        new
                        {
                            Id = 5,
                            City = "Roma",
                            Daily = 592.0,
                            Name = "Hotel Colosseum",
                            Stars = 0
                        },
                        new
                        {
                            Id = 6,
                            City = "Nova Yorque",
                            Daily = 1.0580000000000001,
                            Name = "SIXTY SoHo",
                            Stars = 0
                        },
                        new
                        {
                            Id = 7,
                            City = "Nova Yorque",
                            Daily = 522.0,
                            Name = "YOTEL New York",
                            Stars = 0
                        },
                        new
                        {
                            Id = 8,
                            City = "Rio de Janeiro",
                            Daily = 533.0,
                            Name = "Hotel Arpoador",
                            Stars = 0
                        },
                        new
                        {
                            Id = 9,
                            City = "Rio de Janeiro",
                            Daily = 338.0,
                            Name = "Prodigy Hotel Santos Dumont Airport",
                            Stars = 0
                        });
                });

            modelBuilder.Entity("eFlight.Domain.Features.Reservations.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarId");

                    b.Property<int>("HotelId");

                    b.Property<string>("Name");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("HotelId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("eFlight.Domain.Features.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cpf");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cpf = "03198210054",
                            Name = "Dienisson"
                        });
                });

            modelBuilder.Entity("eFlight.Domain.Features.Reservations.Reservation", b =>
                {
                    b.HasOne("eFlight.Domain.Features.Cars.Car", "Car")
                        .WithMany("Reservations")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("eFlight.Domain.Features.Hotels.Hotel", "Hotel")
                        .WithMany("Reservations")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("eFlight.Domain.Features.Users.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
